//Kitkat balance

export const TOPPING_CATEGORIES = {
  Fruits: [
    {
      id: "cherries",
      label: "Cherries",
      type: "perimeter",
      color: "#d63031",
      shape: "sphere",
      model: "/models/cherries.glb",
      scale: 3,
      yOffset: -0.1,
    },
    {
      id: "strawberries",
      label: "Strawberries",
      type: "perimeter",
      color: "#e84118",
      shape: "cone",
      model: "/models/strawberry.glb",
      scale: 3,
      yOffset: -0.05,
      rotation: [Math.PI, -Math.PI, 0],
    },
    {
      id: "blueberries",
      label: "Blueberries",
      type: "scatter",
      color: "#192a56",
      shape: "sphere",
      scale: 0.1,
    },
    {
      id: "kiwi",
      label: "Kiwi Slices",
      type: "perimeter",
      color: "#6ab04c",
      shape: "cylinder",
      model: "/models/kiwi.glb",
      scale: 3,
      radius: 0.5,
      yOffset: -0.1,
      // rotation: [Math.PI / 2, 0, 0],
    },
    {
      id: "pineapple",
      label: "Pineapple",
      type: "perimeter",
      color: "#f9ca24",
      shape: "box",
      model: "/models/pineapple.glb",
      scale: 1,
      yOffset: -0.1,
      rotation: [Math.PI / 2, 0, Math.PI],
    },
  ],
  Chocolate: [
    {
      id: "choco_chips",
      label: "Choco Chips",
      type: "scatter",
      color: "#2d3436",
      shape: "cone",
      model: "/models/choco_chips.glb",
      scale: 0.1,
    },
    {
      id: "white_chips",
      label: "White Chips",
      type: "scatter",
      color: "#dfe6e9",
      shape: "cone",
      scale: 0.05,
    },
    {
      id: "fudge",
      label: "Fudge Cubes",
      type: "scatter",
      color: "#63421b",
      shape: "box",
      model: "/models/fudge_cubes.glb",
      scale: 1,
    },
    {
      id: "kitkat",
      label: "KitKat",
      type: "side",
      color: "#5d4037",
      model: "/models/kitkat.glb",
      scale: 14, // Reset to reasonable size
      yOffset: -0.1,
      count: 50, 
      radius: 1.50,
      rotation: [0, Math.PI / 2, Math.PI ], // Remove X-rotation so it stands upright
    },
    {
      id: "oreo",
      label: "Oreo",
      type: "surface",
      color: "#2d3436",
      model: "/models/oreo.glb",
      scale: 0.5,
      yOffset: -0.05,
      count: 50,
    },
  ],
  Sprinkles: [
    {
      id: "rainbow_sprinkles",
      label: "Rainbow",
      type: "scatter",
      color: "multi",
      shape: "capsule",
      scale: 0.02,
    },
    {
      id: "pearls",
      label: "Sugar Pearls",
      type: "scatter",
      color: "#ffffff",
      shape: "sphere",
      scale: 0.04,
    },
  ],
  Nuts: [
    {
      id: "almonds",
      label: "Almonds",
      type: "scatter",
      color: "#d1ccc0",
      shape: "box",
      scale: 0.5,
      model: "/models/almonds.glb",
      rotation: [Math.PI, 0, 0],
      count: 300,
    },
    {
      id: "cashews",
      label: "Cashews",
      type: "scatter",
      color: "#f1f2f6",
      shape: "c-shape",
      model: "/models/cashews.glb",
      rotation: [0, 0, 0],
      scale: 0.1,
      // yOffset: -0.1,
      count: 300,
    },
  ],
  Cream: [
    {
      id: "whipped_cream",
      label: "Whipped Cream",
      type: "perimeter",
      color: "#ffffff",
      shape: "torus",
      scale: 0.2,
    },
    {
      id: "roses",
      label: "Buttercream Roses",
      type: "perimeter",
      color: "#fd79a8",
      shape: "rose",
      scale: 0.25,
    },
  ],
  Premium: [
    {
      id: "macarons",
      label: "Macarons",
      type: "perimeter",
      color: "#a29bfe",
      shape: "cylinder",
      scale: 0.05,
      model: "/models/macarons.glb",
      rotation: [Math.PI, 0, 0],
      yOffset: -0.05,
    },
    {
      id: "ferrero",
      label: "Ferrero Rocher",
      type: "perimeter",
      color: "#cd6133",
      shape: "sphere",
      scale: 10,
      model: "/models/ferrero.glb",
      rotation: [Math.PI, 0, 0],
      yOffset: 0.15,
    },
    {
      id: "candles",
      label: "Candles",
      type: "center",
      color: "#74b9ff",
      shape: "cylinder",
      scale: 0.1,
      height: 0.8,
    },
  ],
};

export const RES_PATHS = {
  // Placeholder for future GLTF loads
};
